// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Arc4 = lv_arc_create(ui_Screen5);
    // lv_obj_set_width(ui_Arc4, 150);
    // lv_obj_set_height(ui_Arc4, 150);
    // lv_obj_set_x(ui_Arc4, -12);
    // lv_obj_set_y(ui_Arc4, -20);
    // lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);


    ui_Spinner3 = lv_spinner_create(ui_Screen5, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 50);
    lv_obj_set_height(ui_Spinner3, 50);
    lv_obj_set_x(ui_Spinner3, -72);
    lv_obj_set_y(ui_Spinner3, 78);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xFF40C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}

