// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_TextArea1;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui____initial_actions0;


// SCREEEN: ui_Screen9
void ui_Screen9_screen_init(void);
void lv_ex_img_1(void);
extern lv_obj_t * ui_Screen9;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
